logging.level.org.springframework=info
server.port=8090
springdoc.swagger-ui.path=/swagger-ui

management.endpoints.web.exposure.include=*

# Enable H2 console
spring.h2.console.enabled=true

# Use H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Create schema from entities
spring.jpa.hibernate.ddl-auto=create

# Run data.sql after schema is created
spring.jpa.defer-datasource-initialization=true

# Show SQL in console
spring.jpa.show-sql=true
